# Name of the project
PROJECT_NAME = Quiz_Competition

#Doxyfile folder
DOC = documentation

#All source code files
SRC = src/main.c

#All test source files
TEST_SRC = src/main.c\
test/test_quiz_competition.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = quiz.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html


Build:
	gcc src/main.c test_quiz.c unity/unity.c -Iunity

Run:
	./a.out